apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: no-name
spec:
  template:
    spec:
      containers:
      - name: "h1-h1-passthrou-deployment"
        imagePullPolicy: Always
      nodeSelector:
        workertype: "app"
